import continued_fraction_calculations_number_theoretic_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace continued_fraction_calculations_number_theoretic_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end continued_fraction_calculations_number_theoretic_theorem_canonical_lane_mathlib
end HautevilleHouse
